//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.projct.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchases_Bill()
        {
            this.PurchasesBillDetails = new HashSet<PurchasesBillDetail>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAfterDiscount { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasesBillDetail> PurchasesBillDetails { get; set; }
    }
}
